### ISSUE TITLE
Provide Javascript file without jQuery and Foundation

### ISSUE THREAD

**Issue by vinmassaro** [yaleux/yaleui#2]
A request from our Drupal 8 project. Thanks!

> The YaleUI JS includes jQuery in the minified app.js, which caused conflicts with Drupal's jQuery (and included a duplicate of Foundations's JS).
> 
> It would be helpful if YaleUI provided a JavaScript file without jQuery + Foundation, otherwise the theme could include the YaleUI source and only include the necessary components.

**Comment by adrianacorona** [comment]
Thanks!

With the Yale UI Style Guide, we're trying to have the easiest out-of-the box implementation so that devs can get straight to building their custom apps without having to include additional libraries to make the basics work. 

That being said, if you follow our [Custom Build instructions](https://github.com/yaleux/yaleui#advanced-custom-build), you should be able to pick and choose what you want included in the build... Does a custom build solve your issues?
